import { UserProfile } from "@auth0/nextjs-auth0";
import { useState } from "react";
import { useSelector } from "react-redux";
import { RootState } from "../../redux/store";

type Props = {
  user: UserProfile;
  isLoading: boolean;
};

const HelpTab = () => {
  const isActive = useSelector(
    (state: RootState) => state.persistedReducer.accounts.isActive
  );
  const [tab, setTab] = useState(0);

  return (
    <div className="py-4">
      <h1 className="text-3xl font-bold">AI Query Help</h1>
      <div className="divider"></div>

      <h3 className="text-2xl font-semibold mb-10">
        How to Generate Accurate SQL Queries?
      </h3>

      <p className="mb-2 mr-2">
        To ensure that the SQL queries generated are accurate, users are advised
        to use the column names that are defined in the database schema. For
        example: customer_id, order_id, etc. Even though the AI can figure out
        what the user is trying to say, it is suggested to be as specific with
        the query as possible for best results.
      </p>

      <div className="divider"></div>

      <h3 className="text-2xl font-semibold mb-10">Layout Guide</h3>
      <div className="mb-10">
        <h3 className="text-lg font-semibold mb-4">Query Playground</h3>

        <p className="mb-2 mr-2">
          Query Playground is where users can use AI to generate SQL queries.
          The right pane displays all the tables defined in the database schema
          that the user has created. Users can switch between different
          databases using the dropdown on the top of the right pane.
        </p>

        <p className="mb-2 mr-2">
          The central pane displays all historical SQL queries generated by the
          user for the selected database.
        </p>

        <p className="mb-4 mr-2">
          Users can generate new queries using the query prompt in the central
          pane. In order to make sure that the generated SQL query is accurate,
          users need to provide the context for the SQL query:
        </p>
      </div>
      <div className="py-4  mb-5 overflow-x-auto">
        <table className="table">
          <tbody>
            <tr className="active">
              <td>Create</td>
              <td >Add data to the database</td>
            </tr>
            <tr className="active">
              <td>Read</td>
              <td>Access data from the database</td>
            </tr>
            <tr className="active">
              <td>Update</td>
              <td>Update existing data in the database</td>
            </tr>
            <tr className="active">
              <td>Delete</td>
              <td>Delete data from the database</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="mb-10">
        <h3 className="text-lg font-semibold mb-4">Explain SQL</h3>

        <p className="mb-2">
          Explain SQL is where users can define or paste SQL code and have that
          code explained in simple English.
        </p>
      </div>

      <div className="mb-10">
        <h3 className="text-lg font-semibold mb-4">Settings</h3>

        <p className="mb-2 mr-2">
          Settings is where users can define and edit the database schema. To
          add a new database, use the <span className="italic">Add New</span>{" "}
          option in the dropdown in the top right corner.
        </p>

        <p className="mb-2 mr-2">
          In addition users can define / edit / delete tables in the selected
          database. The column type is not validated and as such, please ensure
          you are defining the database schema correctly.
        </p>
      </div>

      <div className="mb-10">
        <h3 className="text-lg font-semibold mb-4">Profile</h3>

        <p className="mb-2 mr-2">
          Profile is where a user&#39;s email and billing information is
          available. A user is able to manage their own billing and subscribe to
          and cancel from any plan they choose.
        </p>
      </div>
    </div>
  );
};

export default HelpTab;
